services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password # rootユーザーのパスワード
      MYSQL_DATABASE: laboratory_development # Railsアプリが使うDB名
      MYSQL_USER: laboratory_user          # Railsアプリが使うユーザー名
      MYSQL_PASSWORD: password             # Railsアプリが使うパスワード
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev # Dockerfile.dev を使用している場合
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bin/dev" # server.pid削除を追加
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: laboratory_development # dbサービスのMYSQL_DATABASEと合わせる
      DATABASE_USER: laboratory_user          # dbサービスのMYSQL_USERと合わせる
      DATABASE_PASSWORD: password             # dbサービスのMYSQL_PASSWORDと合わせる
    depends_on:
      - db

volumes:
  db-data:
