# Rubyのバージョンを指定
ARG RUBY_VERSION=3.1.4
FROM ruby:$RUBY_VERSION

# Node.jsとYarnのインストールに必要なパッケージ
ARG NODE_MAJOR=18
RUN apt-get update -qq && \
    apt-get install -y build-essential libpq-dev curl gnupg nano && \
    curl -sL https://deb.nodesource.com/setup_$NODE_MAJOR.x | bash - && \
    apt-get install -y nodejs && \
    npm install -g yarn

# 作業ディレクトリの設定
WORKDIR /app

# Gemfileをコピーしてbundle installを実行
COPY Gemfile Gemfile.lock ./
RUN bundle install

# アプリケーションコードをコピー（任意、rails new後に必要）
# COPY . .

# コンテナ起動時に実行するコマンド（rails new後に設定）
# CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
